parser grammar GrammaireParser
options {tokenVocab=GrammaireLexer;}

prog : 		
	CIRCUIT NEWLINE COMMANDES EOF;

CIRCUIT :
	EQCIRCUIT LPAR LISTE_ENTREES RPAR RETURNS LPAR LISTE_SORTIES RPAR NEWLINE
	EQUATIONS NEWINE
	END NEWLINE
;
LISTE_ENTREES :
	LISTE_ENTREES VIRGULE LISTE_ENTREES
|	INTERRUPTEUR
;


 	
